### PR TITLE
✨ Add mockk-junit5 module

### LINKED ISSUE #1: Add module for junit-5 support

### PR DESCRIPTION
**Pull request by erikhuizinga**
Closes #1.

@dragneelfps could you try this version and leave a review (because you opened #1)?

I'm publishing this version ASAP as mockk-junit5:1.0.0-alpha to JCenter, but it might take hours for it to be accepted. Until then, you can get it using:

```groovy
repositories {
    maven {
        url  "https://dl.bintray.com/erikhuizinga/maven" 
    }
}
```

and

```groovy
testImplementation "com.github.erikhuizinga:mockk-junit5:1.0.0-alpha"
```

### CODE REVIEW

**Comment by erikhuizinga** [comment]
I had to publish as a non-SNAPSHOT, so the version name now is `1.0.0-alpha`. I'll update the PR description.

**Comment by dragneelfps** [comment]
@erikhuizinga having examples would be awesome.

**Comment by erikhuizinga** [comment]
@dragneelfps the example has been pushed!

**Comment by erikhuizinga** [comment]
I'll make a similar example for JUnit 4, outside of this PR.

**Comment by dragneelfps** [comment]
LGTM

**Pull request merged**
